package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private BigDecimal id;
     private Lobs lobs;
     private Team team;
     private Title title;
     private String name;
     private BigDecimal graduationyear;
     private String mobile;
     private String email;
     private String major;
     private String faculty;
     private BigDecimal employmentyear;
     private BigDecimal localemploymentyear;
     private String location;
     private Set<Employeeskill> employeeskills = new HashSet<Employeeskill>(0);

    public Employee() {
    }

	
    public Employee( Team team, Title title, String name) {
     
        this.team = team;
        this.title = title;
        this.name = name;
    }
    public Employee(BigDecimal id, Lobs lobs, Team team, Title title, String name, BigDecimal graduationyear, String mobile, String email, String major, String faculty, BigDecimal employmentyear, BigDecimal localemploymentyear, String location, Set<Employeeskill> employeeskills) {
       this.id = id;
       this.lobs = lobs;
       this.team = team;
       this.title = title;
       this.name = name;
       this.graduationyear = graduationyear;
       this.mobile = mobile;
       this.email = email;
       this.major = major;
       this.faculty = faculty;
       this.employmentyear = employmentyear;
       this.localemploymentyear = localemploymentyear;
       this.location = location;
       this.employeeskills = employeeskills;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Lobs getLobs() {
        return this.lobs;
    }
    
    public void setLobs(Lobs lobs) {
        this.lobs = lobs;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public Title getTitle() {
        return this.title;
    }
    
    public void setTitle(Title title) {
        this.title = title;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getGraduationyear() {
        return this.graduationyear;
    }
    
    public void setGraduationyear(BigDecimal graduationyear) {
        this.graduationyear = graduationyear;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }
    public BigDecimal getEmploymentyear() {
        return this.employmentyear;
    }
    
    public void setEmploymentyear(BigDecimal employmentyear) {
        this.employmentyear = employmentyear;
    }
    public BigDecimal getLocalemploymentyear() {
        return this.localemploymentyear;
    }
    
    public void setLocalemploymentyear(BigDecimal localemploymentyear) {
        this.localemploymentyear = localemploymentyear;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set<Employeeskill> getEmployeeskills() {
        return this.employeeskills;
    }
    
    public void setEmployeeskills(Set<Employeeskill> employeeskills) {
        this.employeeskills = employeeskills;
    }




}


