package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Levellookup generated by hbm2java
 */
public class Levellookup  implements java.io.Serializable {


     private BigDecimal id;
     private String levelname;
     private Set<Employeeskill> employeeskillsForSkilllevel = new HashSet<Employeeskill>(0);
     private Set<Employeeskill> employeeskillsForTargetlevel = new HashSet<Employeeskill>(0);

    public Levellookup() {
    }

	
    public Levellookup(BigDecimal id, String levelname) {
        this.id = id;
        this.levelname = levelname;
    }
    public Levellookup(BigDecimal id, String levelname, Set<Employeeskill> employeeskillsForSkilllevel, Set<Employeeskill> employeeskillsForTargetlevel) {
       this.id = id;
       this.levelname = levelname;
       this.employeeskillsForSkilllevel = employeeskillsForSkilllevel;
       this.employeeskillsForTargetlevel = employeeskillsForTargetlevel;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getLevelname() {
        return this.levelname;
    }
    
    public void setLevelname(String levelname) {
        this.levelname = levelname;
    }
    public Set<Employeeskill> getEmployeeskillsForSkilllevel() {
        return this.employeeskillsForSkilllevel;
    }
    
    public void setEmployeeskillsForSkilllevel(Set<Employeeskill> employeeskillsForSkilllevel) {
        this.employeeskillsForSkilllevel = employeeskillsForSkilllevel;
    }
    public Set<Employeeskill> getEmployeeskillsForTargetlevel() {
        return this.employeeskillsForTargetlevel;
    }
    
    public void setEmployeeskillsForTargetlevel(Set<Employeeskill> employeeskillsForTargetlevel) {
        this.employeeskillsForTargetlevel = employeeskillsForTargetlevel;
    }




}


