package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Skilltrainingrequired generated by hbm2java
 */
public class Skilltrainingrequired  implements java.io.Serializable {


     private BigDecimal id;
     private Employeeskill employeeskill;
     private BigDecimal trainingid;
     private String trainingname;

    public Skilltrainingrequired() {
    }

	
    public Skilltrainingrequired(BigDecimal id, Employeeskill employeeskill, BigDecimal trainingid) {
        this.id = id;
        this.employeeskill = employeeskill;
        this.trainingid = trainingid;
    }
    public Skilltrainingrequired(BigDecimal id, Employeeskill employeeskill, BigDecimal trainingid, String trainingname) {
       this.id = id;
       this.employeeskill = employeeskill;
       this.trainingid = trainingid;
       this.trainingname = trainingname;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Employeeskill getEmployeeskill() {
        return this.employeeskill;
    }
    
    public void setEmployeeskill(Employeeskill employeeskill) {
        this.employeeskill = employeeskill;
    }
    public BigDecimal getTrainingid() {
        return this.trainingid;
    }
    
    public void setTrainingid(BigDecimal trainingid) {
        this.trainingid = trainingid;
    }
    public String getTrainingname() {
        return this.trainingname;
    }
    
    public void setTrainingname(String trainingname) {
        this.trainingname = trainingname;
    }




}


