package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Skillcategory generated by hbm2java
 */
public class Skillcategory  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set<Skilltype> skilltypes = new HashSet<Skilltype>(0);

    public Skillcategory() {
    }

	
    public Skillcategory(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Skillcategory(BigDecimal id, String name, Set<Skilltype> skilltypes) {
       this.id = id;
       this.name = name;
       this.skilltypes = skilltypes;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Skilltype> getSkilltypes() {
        return this.skilltypes;
    }
    
    public void setSkilltypes(Set<Skilltype> skilltypes) {
        this.skilltypes = skilltypes;
    }




}


