package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Skillsourcetype generated by hbm2java
 */
public class Skillsourcetype  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set<Skillsource> skillsources = new HashSet<Skillsource>(0);

    public Skillsourcetype() {
    }

	
    public Skillsourcetype(BigDecimal id) {
        this.id = id;
    }
    public Skillsourcetype(BigDecimal id, String name, Set<Skillsource> skillsources) {
       this.id = id;
       this.name = name;
       this.skillsources = skillsources;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Skillsource> getSkillsources() {
        return this.skillsources;
    }
    
    public void setSkillsources(Set<Skillsource> skillsources) {
        this.skillsources = skillsources;
    }




}


