package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Skillspecialization generated by hbm2java
 */
public class Skillspecialization  implements java.io.Serializable {


     private BigDecimal id;
     private Skilltype skilltype;
     private String name;
     private String description;
     private Set<Employeeskill> employeeskills = new HashSet<Employeeskill>(0);

    public Skillspecialization() {
    }

	
    public Skillspecialization(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Skillspecialization(BigDecimal id, Skilltype skilltype, String name, String description, Set<Employeeskill> employeeskills) {
       this.id = id;
       this.skilltype = skilltype;
       this.name = name;
       this.description = description;
       this.employeeskills = employeeskills;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Skilltype getSkilltype() {
        return this.skilltype;
    }
    
    public void setSkilltype(Skilltype skilltype) {
        this.skilltype = skilltype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Employeeskill> getEmployeeskills() {
        return this.employeeskills;
    }
    
    public void setEmployeeskills(Set<Employeeskill> employeeskills) {
        this.employeeskills = employeeskills;
    }




}


