package Mapping;
// Generated Jun 19, 2015 3:46:43 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Skillsource generated by hbm2java
 */
public class Skillsource  implements java.io.Serializable {


     private BigDecimal id;
     private Skillsourcetype skillsourcetype;
     private String sourcename;
     private Set<Employeeskill> employeeskills = new HashSet<Employeeskill>(0);

    public Skillsource() {
    }

	
    public Skillsource(BigDecimal id) {
        this.id = id;
    }
    public Skillsource(BigDecimal id, Skillsourcetype skillsourcetype, String sourcename, Set<Employeeskill> employeeskills) {
       this.id = id;
       this.skillsourcetype = skillsourcetype;
       this.sourcename = sourcename;
       this.employeeskills = employeeskills;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Skillsourcetype getSkillsourcetype() {
        return this.skillsourcetype;
    }
    
    public void setSkillsourcetype(Skillsourcetype skillsourcetype) {
        this.skillsourcetype = skillsourcetype;
    }
    public String getSourcename() {
        return this.sourcename;
    }
    
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename;
    }
    public Set<Employeeskill> getEmployeeskills() {
        return this.employeeskills;
    }
    
    public void setEmployeeskills(Set<Employeeskill> employeeskills) {
        this.employeeskills = employeeskills;
    }




}


